//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int ID { get; set; }
        public int NationalID { get; set; }
        public int ProvinceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string KeyWord { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public int Order { get; set; }
    
        public virtual National National { get; set; }
        public virtual Province Province { get; set; }
    }
}
