//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryPicture
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Alt { get; set; }
        public string Url { get; set; }
        public string FileName { get; set; }
        public int Order { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }
        public long ContentLength { get; set; }
        public bool IsActive { get; set; }
        public int Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
