//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.CategoryPictures = new HashSet<CategoryPicture>();
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ListParentID { get; set; }
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Content { get; set; }
        public string Url { get; set; }
        public int Order { get; set; }
        public int Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public int Level { get; set; }
        public int Position { get; set; }
        public bool IsAdmin { get; set; }
        public string AdminUrl { get; set; }
    
        public virtual ICollection<CategoryPicture> CategoryPictures { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
