//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long ID { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
