//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderPicture
    {
        public int ID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Alt { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }
        public Nullable<long> ContentLength { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsAvartar { get; set; }
        public string BackLink { get; set; }
    
        public virtual TourProvider TourProvider { get; set; }
    }
}
