//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Areas = new HashSet<Area>();
            this.Districts = new HashSet<District>();
        }
    
        public int ID { get; set; }
        public int NationalID { get; set; }
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public string Description { get; set; }
        public string KeyWord { get; set; }
        public bool IsActive { get; set; }
        public int Order { get; set; }
        public int Position { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string Avartar { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual National National { get; set; }
    }
}
