//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAgenda
    {
        public int ID { get; set; }
        public int TourID { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Description { get; set; }
        public int NationalID { get; set; }
        public int ProvinceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsActivate { get; set; }
        public string Name { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
