//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.TourAgendas = new HashSet<TourAgenda>();
            this.TourPictures = new HashSet<TourPicture>();
            this.TourPrices = new HashSet<TourPrice>();
            this.Comments = new HashSet<Comment>();
            this.TourSuggestions = new HashSet<TourSuggestion>();
            this.TourMarketings = new HashSet<TourMarketing>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> Duration { get; set; }
        public string KeyWord { get; set; }
        public string Content { get; set; }
        public string Policy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public int Order { get; set; }
        public string ListPayment { get; set; }
        public int TourTypeID { get; set; }
        public Nullable<int> TourThemeID { get; set; }
        public string ListComfort { get; set; }
        public int DepartureNationalID { get; set; }
        public int DepartureProvinceID { get; set; }
        public Nullable<int> DepartureDistrictID { get; set; }
        public Nullable<int> DepartureAreaID { get; set; }
        public int DestinationNationalID { get; set; }
        public int DestinationProvinceID { get; set; }
        public Nullable<int> DestinationDistrictID { get; set; }
        public Nullable<int> DestinationAreaID { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Url { get; set; }
        public string Promotion { get; set; }
        public bool IsPromotion { get; set; }
        public Nullable<int> TourProviderID { get; set; }
        public string LinkToSite { get; set; }
        public Nullable<int> NumberGuest { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual TourTheme TourTheme { get; set; }
        public virtual TourType TourType { get; set; }
        public virtual ICollection<TourAgenda> TourAgendas { get; set; }
        public virtual ICollection<TourPicture> TourPictures { get; set; }
        public virtual ICollection<TourPrice> TourPrices { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<TourSuggestion> TourSuggestions { get; set; }
        public virtual ICollection<TourMarketing> TourMarketings { get; set; }
    }
}
