//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_tourEntities : DbContext
    {
        public admin_tourEntities()
            : base("name=admin_tourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryPicture> CategoryPictures { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Config> Configs { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<National> Nationals { get; set; }
        public DbSet<New> News { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<Social> Socials { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Support> Supports { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Tour> Tours { get; set; }
        public DbSet<TourAgenda> TourAgendas { get; set; }
        public DbSet<TourPicture> TourPictures { get; set; }
        public DbSet<TourPrice> TourPrices { get; set; }
        public DbSet<TourProvider> TourProviders { get; set; }
        public DbSet<TourTheme> TourThemes { get; set; }
        public DbSet<TourType> TourTypes { get; set; }
        public DbSet<ProviderPicture> ProviderPictures { get; set; }
        public DbSet<TourActivity> TourActivities { get; set; }
        public DbSet<TourSuggestion> TourSuggestions { get; set; }
        public DbSet<TourMarketing> TourMarketings { get; set; }
    }
}
