//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourPrice
    {
        public long ID { get; set; }
        public int TourID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NumberGuest { get; set; }
        public bool IsContact { get; set; }
        public string Description { get; set; }
        public string LinkBooking { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual TourProvider TourProvider { get; set; }
    }
}
