//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourActivity
    {
        public TourActivity()
        {
            this.TourSuggestions = new HashSet<TourSuggestion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string KeyWord { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string Type { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int NationalID { get; set; }
        public int ProvinceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        public virtual ICollection<TourSuggestion> TourSuggestions { get; set; }
    }
}
